### ISSUE TITLE
Add ability to name agents

### ISSUE THREAD

**Issue by agardnerIT** [agardnerIT/opamp-server-py#9]
Agents have a very user-unfriendly UUID. The user should be able to set a value (it feels like this should be an `identifying_attribute` but I couldn't get this to work). I tried following [this](https://opentelemetry.io/docs/specs/opamp/#agentdescriptionidentifying_attributes) which says I should be able to do:

```
extensions:
  opamp:
    server:
      http:
        endpoint: http://127.0.0.1:4320/v1/opamp
        polling_interval: 5s
    agent_description:
      identifying_attributes:
        service.name: "foo"
```

But that caused an error:

```
error decoding 'extensions': error reading configuration for "opamp": decoding failed due to the following error(s):

'agent_description' has invalid keys: identifying_attributes
```

## Workaround - Use Non-Identifying Attributes

I also can't find anything in the semconvs about how an agent name should be specified. For now, I'll use `agent.name` in `non_identifying_attributes`
